# Programming fundamental concepts: Modules and Numpy

*This assignment is not obligatory*

## Introduction

In the last tutorial we have covered the basics of Python programming, including variables, data types, and control structures. We also introduced some fundamental programming concepts such as loops and conditionals. In this tutorial we will take a closer look at functions and how to use them effectively in your code. We will not only use built-in functions but also import them from external libraries.

Throughout this tutorial, we will also focus on file handling in Python, including reading from and writing to files. This is an essential skill, since we will be working a lot with data stored in files.

### Useful tools

During coding, you will often need to look up how certain functions work. There are several useful tools to help you with this:
- The [Python documentation](https://docs.python.org/3/) or library documentation such as [NumPy](https://numpy.org/doc/stable/) and [Pandas](https://pandas.pydata.org/pandas-docs/stable/) are great resources.
- AI tools like [ChatGPT](https://chat.openai.com/) and [Copilot](https://github.com/features/copilot).
- Online forums and communities such as [Stack Overflow](https://stackoverflow.com/).

## Python packages

for this assignment we will be using the following packages:
- `numpy`: for numerical operations
- `pandas`: for data manipulation and analysis
- `os`: for interacting with the operating system

These should be installed in your Python environment. If you haven't installed them yet, you can do so using conda:

```bash
conda install numpy
```

> **Task 1:**
>
> Let's start by importing the necessary libraries.
>
> ```python
> import numpy as np
> import pandas as pd
> import os
> ```

In [6]:
import numpy as np
import pandas as pd
import os

### Numpy
Numpy (numpy documentation: https://numpy.org/doc/stable/) is one of the most popular libraries for numerical computing in Python. It provides support for arrays, matrices, and a wide range of mathematical functions to operate on these data structures. Numpy is particularly useful for handling large datasets and performing complex mathematical operations efficiently. You will be using this library extensively throughout MUDE.

We will start by creating a simple array using Numpy after which we will focus on indexing and slicing. Indexing and slicing works similarly to Python lists, but with some additional features. 

A list of useful numpy functions:

- np.array(): Create an array
- np.arange(): Create an array with a range of values
- np.zeros(): Create an array filled with zeros
- np.ones(): Create an array filled with ones
- np.eye(): Create an identity matrix
- np.reshape(): Reshape an array
- np.transpose(): Transpose an array
- np.concatenate(): Concatenate arrays
- np.split(): Split an array
- np.mean(): Compute the mean of an array
- np.sum(): Compute the sum of an array
- np.max(): Find the maximum value in an array
- np.min(): Find the minimum value in an array
- np.std(): Compute the standard deviation of an array
- np.dot(): Compute the dot product of two arrays
- np.cross(): Compute the cross product of two arrays
- np.linalg.inv(): Compute the inverse of a matrix
- np.linalg.det(): Compute the determinant of a matrix
- np.random.rand(): Generate random numbers
- np.random.randn(): Generate random numbers from a standard normal distribution

In [ ]:
# Create a 1D array
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(type([1,2,3]))

# Create a 2D array
arr2 = np.array([[1,2,3],
                [4,5,6]])

print('arr2:',arr2)
print('dtype:',arr2.dtype) # dtype is a built-in function for numpy, telling us what kind of variables are inside the list (array)

# Append a new row to the 2D array
# arr2_new = np.append(arr2, [7,8,9]) # now it becomes a 1D. it is because it has access parameter, it doesn't know unless we give instructions through command
arr2_new = np.append(arr2, [[7,8,9]], axis=0) # the brackets need to be doubled, if not it doesn't know it should be the third row for the matrix
# using append, need to put it in a new function (place), if not that the result is not saved
print('shape:', arr2.shape)
print(arr2_new)

[1 2 3 4 5]
<class 'numpy.ndarray'>
<class 'list'>
arr2: [[1 2 3]
 [4 5 6]]
dtype: int64
shape: (2, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]

> **Task 2:**
>
> We will now create a np.array with 10 rows and 3 columns. The first column is filled from 1 to 10, the second column is filled with the squares of the first column, and the third column is filled with the cubes of the first column. After we have created the array we will save it to a file.
>
> I will show you two ways to do this:
> - Starting with an empty array and filling it in a loop.
> - creating 3 separate arrays for each column and then combining them.

In [32]:
# Method 1
matrix1 = np.zeros((10,3))
# print(matrix1)
# print(matrix1.shape)

matrix1[:,0] = [1,2,3,4,5,6,7,8,9,10]
# print(matrix1)

for i in range(2):
    matrix1[:,i+1] = matrix1[:,0] ** (i+2)
# print(matrix1)
    

# Method 2
col1 = np.array([1,2,3,4,5,6,7,8,9,10])
# print(col1)
col2 = col1 ** 2
# print(col2)
col3 = col1 ** 3
# print(col3)

matrix2 = np.column_stack([col1,col2,col3])
# print(matrix2)

# Lets check
print(matrix1 == matrix2) # == is to check whether these two things are equal
print((matrix1 == matrix2).all())
print((matrix1 == matrix2).any())

# save the file as csv
np.savetxt('matrix.csv', matrix1, delimiter=',', header='col1,col2,col3') # will save in the same folder as where we put this coding file

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]
True
True

> **Task 3:**
>
> Now we will use some of numpy's powerful features to manipulate our data. Let's try some matrix operations. First, we will create a 3x3 matrix and perform some basic operations on it.

In [47]:
# Perform basic operations
np.set_printoptions(precision=3, suppress=True) # only applies to arrays, for single number still need to format independently

my_array = np.array([[6,3,2], [9,4,2], [12,5,3]])
print("Original array:")
print(my_array)

print("Transposed array:")
print(my_array.T)

print("Array multiplied by 2:")
print (my_array * 2)

# Matrix multiplication
my_array2 = np.array([[-1,-3], [2,-4], [6,-2]])
print("Matrix multiplication result:")
print(my_array @ my_array2)

# Compute the inverse and determinant
print("Inverse of the original array:")
print(np.linalg.inv(my_array))

print("Determinant of the original array:")
print(f"{np.linalg.det(my_array):.3f}")
# print(np.linalg.det(my_array))

Original array:
[[ 6  3  2]
 [ 9  4  2]
 [12  5  3]]
Transposed array:
[[ 6  9 12]
 [ 3  4  5]
 [ 2  2  3]]
Array multiplied by 2:
[[12  6  4]
 [18  8  4]
 [24 10  6]]
Matrix multiplication result:
[[ 12 -34]
 [ 11 -47]
 [ 16 -62]]
Inverse of the original array:
[[-0.667 -0.333  0.667]
 [ 1.     2.    -2.   ]
 [ 1.    -2.     1.   ]]
Determinant of the original array:
-3.000

## os
Now that we have our data saved in a CSV file, we can use the `os` module to interact with the file system. For example, we can check if the file exists, remove it, or rename it.

some useful os functions:
- `os.path.exists(path)`: Check if a file or directory exists
- `os.remove(path)`: Remove a file
- `os.rename(old, new)`: Rename a file or directory
- `os.listdir(path)`: List all files and directories in a directory
- `os.getcwd()`: Get the current working directory
- `os.chdir(path)`: Change the current working directory
- `os.mkdir(path)`: Create a new directory
- `os.makedirs(path)`: Create a new directory and all intermediate directories
- `os.path.join(path, *paths)`: Join one or more path components intelligently

In [ ]:
# List all files in the current directory
os.listdir() # if nothing is inside the bracket, it will read the folder this file currently in
# but we can also add another directory folders to be read using this code

# Get the current working directory
os.getcwd()

['.git',
 '1_VS_share.ipynb',
 '2_IntelliSense.ipynb',
 '3_matrix_vector_manipulations.ipynb',
 '4_python_tutorial.ipynb',
 'CITATION.cff',
 'LICENSE',
 'matrix.csv',
 'README.md',
 'requirements.txt',
 'tests']

## Pandas

Now we will use pandas to import our newly created CSV file and perform some data analysis. We could also do this with other libraries, such as numpy, but pandas is specifically designed for data manipulation and analysis.

Some useful pandas functions include:

- `pd.read_csv()`: Read a CSV file into a DataFrame.
- `df.head()`: Display the first few rows of a DataFrame.
- `df.describe()`: Generate descriptive statistics.

> **Task 4:**
>
> Import our my_array.csv file using pandas and display the first few rows as well as the summary statistics.

In [68]:
# Import our my_array.csv file using pandas
df = pd.read_csv('matrix.csv')
# df -> this gives a nice format. if want to look at the raw files, use print function
print(type(df))
print(df.dtypes) # this is to read types of data for each column

# Display the first few rows
df.head()
df.sample(5) # this is to look at multiple rows, more than when using the head function

<class 'pandas.DataFrame'>
# col1    float64
col2      float64
col3      float64
dtype: object

   # col1  col2   col3
8     9.0  81.0  729.0
3     4.0  16.0   64.0
4     5.0  25.0  125.0
7     8.0  64.0  512.0
0     1.0   1.0    1.0

In [72]:
df[['col2','col3']]

    col2    col3
0    1.0     1.0
1    4.0     8.0
2    9.0    27.0
3   16.0    64.0
4   25.0   125.0
5   36.0   216.0
6   49.0   343.0
7   64.0   512.0
8   81.0   729.0
9  100.0  1000.0

In [71]:
df.iloc[:,:3]

   # col1   col2    col3
0     1.0    1.0     1.0
1     2.0    4.0     8.0
2     3.0    9.0    27.0
3     4.0   16.0    64.0
4     5.0   25.0   125.0
5     6.0   36.0   216.0
6     7.0   49.0   343.0
7     8.0   64.0   512.0
8     9.0   81.0   729.0
9    10.0  100.0  1000.0

In [ ]:
# Display the summary statistics
df.describe()

# Transform the data
print(df['col2'] * 2)
print(df['col2'] ** 2)
print(df['col2'].astype(int))
# these functions do not overwrite the original data, like in numpy

# Create numpy array from DataFrame
df.iloc[:,:3].to_numpy()

In [61]:
df['col4'] = ['a','b','c','d','e','f','g','h','i','j']
print(df)

   # col1   col2    col3 col4
0     1.0    1.0     1.0    a
1     2.0    4.0     8.0    b
2     3.0    9.0    27.0    c
3     4.0   16.0    64.0    d
4     5.0   25.0   125.0    e
5     6.0   36.0   216.0    f
6     7.0   49.0   343.0    g
7     8.0   64.0   512.0    h
8     9.0   81.0   729.0    i
9    10.0  100.0  1000.0    j

> By Berend Bouvy, Delft University of Technology. CC BY 4.0, more info [on the Credits page of Workbook](https://mude.citg.tudelft.nl/workbook-2025/credits.html).